apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: fakelogs
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fakelogs
  template:
    metadata:
      labels:
        app: fakelogs
    spec:
      containers:
      - name: fakelogs
        image: cloudhero/fakelogs
        command: ["/bin/sh", "-c"]
        args: ["./main > /app/log/app.log"]
        volumeMounts:
        - name: log-volume
          mountPath: /app/log
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      - name: fluentbit
#       image: fluent/fluent-bit:1.0.6
        image: fluent/fluent-bit:1.7.2
        volumeMounts:
        - name: log-volume
          mountPath: /app/log
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/parsers_springboot.conf
          subPath: parsers_springboot.conf
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      - name: logrotate
        image: cloudhero/logrotate
        volumeMounts:
        - name: log-volume
          mountPath: /app/log
        - name: config
          mountPath: /etc/logrotate.conf
          subPath: logrotate.conf
        - name: config
          mountPath: /etc/logrotate.d/logrotate-java.conf
          subPath: logrotate-java.conf
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: config
        configMap:
          name: fakelogs-configmap
