apiVersion: v1
kind: ConfigMap
metadata:
  name: fakelogs-configmap
  namespace: demo
  labels:
    component: fakelogs-configmap
data:
  logrotate.conf: |-
    weekly
    rotate 4
    create
    tabooext + .apk-new
    compress
    include /etc/logrotate.d
  logrotate-java.conf: |-
    /app/log/app.log {
            hourly
            size 100M
            missingok
            rotate 1
            compress
            notifempty
            create 0640 root root
    }
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name             tail
        Path             /app/log/app.log
        Multiline        on

    [OUTPUT]
        Name                    gelf
        Match                   *
        Host                    graylog-test.babylon-dev.loc
        Port                    12201
        Mode                    udp
        Gelf_Short_Message_Key  data

    [PARSER]
        Name        docker
        Format      json
        Regex       /^(?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]+)\s+(?<log_level>[Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)\s+(?<pid>[0-9]+)\s+---\s+\[(?<thread>.*)\]\s+(?<class_name>.*)\s+:\s+(?<message>.*)$/
        Time_Key    time
        Time_Format %Y-%m-%
