apiVersion: v1
kind: ConfigMap
metadata:
  name: fakelogs-configmap
  namespace: demo
  labels:
    component: fakelogs-configmap
data:
  logrotate.conf: |-
    weekly
    rotate 4
    create
    tabooext + .apk-new
    compress
    include /etc/logrotate.d
  logrotate-java.conf: |-
    /app/log/app.log {
            hourly
            size 100M
            missingok
            rotate 1
            compress
            notifempty
            create 0640 root root
    }
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers_springboot.conf

    [INPUT]
        Name             tail
        Path             /app/log/app.log
        Multiline        on
        Parser_Firstline springboot

    [FILTER]
        Name                    kubernetes
        Match                   *.log
        Merge_Log_Key           log
        Merge_Log               On
        Keep_Log                Off
        Annotations             Off
        Labels                  Off

    [OUTPUT]
        Name                    gelf
        Match                   *
        Host                    graylog-test.babylon-dev.loc
        Port                    12201
        Gelf_Short_Message_Key  log
  parsers_springboot.conf: |-
    [PARSER]
        Name        springboot
        Format      regex
        Regex       /(?<time>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)/
        Time_Key    time
        Time_Format %b %d %H:%M:%S
