apiVersion: v1
kind: Service
metadata:
  labels:
    run: graylog-external
  name: graylog-external
  namespace: demo
spec:
  externalName: graylog-test.babylon-dev.loc
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: ExternalName

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    run: graylog-external
  name: graylog-external
  namespace: demo
spec:
  virtualhost:
    fqdn: graylog-test-ui.babylon-dev.loc
  routes:
  - conditions:
    - prefix: /
    services:
    - name: graylog-external
      port: 9000
    requestHeadersPolicy:
      set:
      - name: Host
        value: graylog-test.babylon-dev.loc
      - name: X-Graylog-Server-URL
        value: http://graylog-test-ui.babylon-dev.loc
