apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: kuard
  name: kuard
  annotations:
    projectcontour.io/ingress.class: contour-internal
  namespace: demo
spec:
  virtualhost:
    fqdn: kuard.babylon-dev.loc
  routes:
  - services:
    - name: kuard
      port: 8080
