apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: kuard
  name: kuard
  annotations:
    projectcontour.io/ingress.class: contour-internal
spec:
  virtualhost:
    fqdn: kuard.babylon.lol
  routes:
  - services:
    - name: kuard
      port: 8080

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: kuard-ext
  name: kuard-ext
# annotations:
#   projectcontour.io/ingress.class: contour-external
spec:
  virtualhost:
    fqdn: kuard-ext.babylon.lol
  routes:
  - services:
    - name: kuard
      port: 8080
