apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - kuard-httpproxy.yaml
  - graylog-external.yaml
  - fakelogs-deploy.yaml
  - fluent-bit-config.yaml
patchesStrategicMerge:
